### ISSUE TITLE
fail to spawn VM instances from image "windows-server-2019" due to its denying ssh_key

### ISSUE THREAD

**Issue by thisislj** [G-Core/gcorelabscloud-go#15]
Hi,

I'm having trouble to use this library to spawn VM instances from image "windows-server-2019", 

I instantiate a `createOpts := instances.CreateOpts{valid configs}` and then call `instances.Create(client, createOpts`) to launch vm.
VM creation request then failed and complained:
`create results err: Image a6a2xxxx-xxxx-xxxx-xxxx-xxxxxxxx0eb0 has a deny ssh_key property: keypair_name can not be used.`

So it seems to me that instances.CreateOpts  always has a "Keypair" in the request but Windows image is configured to deny it. 

I can workaround this issue by overriding default `instances.ToInstanceCreateMap` to purge the `keypair_name` field. 
```
type CreateWinOpts struct {
	createOpts instances.CreateOpts
}

func (opts CreateWinOpts) ToInstanceCreateMap() (map[string]interface{}, error) {
	b, err := opts.createOpts.ToInstanceCreateMap()
	if err != nil {
		return nil, err
	}
	delete(b, "keypair_name")
	return b, nil
}

func (opts CreateWinOpts) Validate() error {
	return opts.createOpts.Validate()
}
```

It's a bit inconvenient. It would be great if you can make this field optional for creating windows images.

Best regards,

Jason

**Comment by 0ndi** [comment]
fixed in v0.4.21, sorry for waiting
