### ISSUE TITLE
could you please add metadata to snapshot createOpts

### ISSUE THREAD

**Issue by thisislj** [G-Core/gcorelabscloud-go#19]
Hi,

G-Core cloud snapshot now can have metadata, https://apidocs.gcorelabs.com/cloud#operation/SnapshotViewSet.post

Could you please update this library so that we can add metadata to new snapshot on creation?
https://github.com/G-Core/gcorelabscloud-go/blob/master/gcore/snapshot/v1/snapshots/requests.go#L56-L60

Thanks!
Jason

**Comment by 0ndi** [comment]
Hi, we added metadata in last release(v0.4.20).
